#!/bin/bash

for folder in {yabai,skhd,sketchybar,zsh,nvim,gitui,lazygit,aider}; do
  stow -t "$HOME/.config/$folder" "$folder" --ignore "DS_Store"
done

stow -t "$HOME/Library/Application Support/com.mitchellh.ghostty" "ghostty" --ignore "DS_Store"
