#!/bin/sh

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGINS="$HOME/.config/sketchybar/plugins"
ITEMS="$HOME/.config/sketchybar/items"
UTILS="$HOME/.config/sketchybar/utils"

# Source these once and all child processes will inherit them instead
# of each sourcing for themselves
source "$UTILS/colors.sh"
source "$UTILS/icons.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
    position=top     \
    sticky=off       \
    padding_left=10  \
    padding_right=10 \
    margin=10        \
    corner_radius=10 \
    y_offset=8       \
    blur_radius=30   \
    color=0x15ffffff

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Bold:17.0"  \
    icon.color=0xffffffff                 \
    label.font="Hack Nerd Font:Bold:14.0" \
    label.color=0xffffffff                \
    padding_left=5                        \
    padding_right=5                       \
    label.padding_left=4                  \
    label.padding_right=4                 \
    icon.padding_left=4                   \
    icon.padding_right=4

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

source $ITEMS/mission_control.sh

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

source $ITEMS/front_app.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source $ITEMS/clock.sh
source $ITEMS/wifi.sh
source $ITEMS/volume.sh
source $ITEMS/battery.sh
# source $ITEMS/vpn.sh
source $ITEMS/system.sh
# source $ITEMS/music.sh
source $ITEMS/media.sh
# source $ITEMS/btc.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
