#!/bin/sh

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGINS="$HOME/.config/sketchybar/plugins"
ITEMS="$HOME/.config/sketchybar/items"
UTILS="$HOME/.config/sketchybar/utils"

# Source these once and all child processes will inherit them instead
# of each sourcing for themselves
source "$UTILS/colors.sh"
source "$UTILS/icons.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=25        \
    position=bottom     \
    sticky=off       \
    color=0xff1a1b26
# color=0x00000000 \
    # y_offset=8       \

    # blur_radius=30   \

    ##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

FONT="SF Pro"

sketchybar --default icon.font="$FONT:Bold:17.0"  \
    label.font="$FONT:Bold:14.0"          \
    label.color=0xffc0caf5                \
    label.padding_left=5                  \
    label.padding_right=5                 \
    icon.padding_left=5                   \
    icon.padding_right=5                  \
    background.color=0xff1a1b26           \
    background.corner_radius=8            \
    background.padding_right=5            \
    background.padding_left=5             \
    background.height=25                  \

    ##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

##### Left Items #####

source $ITEMS/mission_control.sh
source $ITEMS/front_app.sh

##### Center Items

##### Right Items #####

source $ITEMS/clock.sh
source $ITEMS/wifi.sh
source $ITEMS/volume.sh
source $ITEMS/vpn.sh
source $ITEMS/battery.sh
source $ITEMS/system.sh
source $ITEMS/media.sh
source $ITEMS/bitcoin.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
