#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                0.5            \
    window_opacity_duration      0.2            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.9            \
    window_opacity               on             \
    window_animation_duration    0.3            \
    window_animation_frame_rate  30             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           on             \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    external_bar all:35:0

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label messaging
yabai -m space 3 --label web
yabai -m space 4 --label time
yabai -m space 5 --label media

# add apps to certain spaces
yabai -m rule --add app="^MailMate$" space=messaging
yabai -m rule --add app="^Messages$" space=messaging
yabai -m rule --add app="^Slack$" space=messaging

yabai -m rule --add app="^kitty$" space=code
yabai -m rule --add app="^Xcode$" space=code

yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app="^Firefox$" space=web

yabai -m rule --add app="^Things$" space=time
yabai -m rule --add app="^Calendar$" space=time

yabai -m rule --add app="^Music$" space=media

# turn off management for specific apps
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Mullvad VPN" manage=off

# When I close or minimize a window the next window in the stack should be focused
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
