alias activate="source venv/bin/activate"
alias fzf="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias ls="eza --all --long --git --header --icons"
alias cd="z"
alias lg="lazygit"
alias src="source ~/.config/zsh/.zshrc ~/.config/.zshenv ~/.config/.zprofile"
alias n="/opt/homebrew/bin/nvim"
alias nn="/usr/local/bin/nvim" # Neovim built from source
alias rg="rg --hidden"
help() {
  "$@" --help 2>&1 | bat --plain --language=help
}
alias pd="pandoc"
alias pddm="pandoc -f docx -t markdown --markdown-headings atx"
alias pdmh="pandoc -f markdown -t html"
alias pdmd="pandoc -f markdown -t docx"
alias pdmp="pandoc -f markdown -t pdf"
alias sed="gsed"
alias time="gtime"
alias nd="neovide"
alias :q="exit"
alias exe="chmod +x"
alias emailer="~/code/emailer/emailer"
alias icat="kitten icat"
alias love="/Applications/love.app/Contents/MacOS/love"

alias b="brew"
alias bi="brew install"
alias bun="brew uninstall"
alias bic="brew install --cask"
alias bunc="brew uninstall --cask"
alias bs="brew search"
alias bin="brew info"
alias bsc="brew search --cask"
alias bu="brew upgrade"
alias buc="brew upgrade --cask"

alias cr="cargo run"
alias crr="cargo run --release"
alias cb="cargo build"
alias cbr="cargo build --release"
alias ccl="cargo clean"
alias ca="cargo add"
alias crm="cargo remove"
alias cbn="cargo bench"
alias ct="cargo test"
alias cf="cargo fmt"
alias cff="cargo fix"

alias nb="cd target; cmake --build . --config Debug; cd .."
alias nbr="cd target; cmake --build . --config Release; cd .."
alias ncl="cd target; for file in build-*.ninja; do; ninja -f \"\$file\" clean; done; cd .."

alias aider="aider --config ~/.aider.conf.yaml"
